### ISSUE TITLE
mirror the releases

### ISSUE THREAD

**Issue by ivg** [mor1/ocaml-bitstring#1]
I'm wondering, can you also mirror the releases? So that the next time google will change their urls without any backward compatibility the packaged (and all it dependents) will not broke. There is a `mirror` field in `url` file, that we can use. 

See corresponding issue: ocaml/opam-repository#7326

**Comment by mor1** [comment]
Hi; Happy to do so if you can point me to instructions how! I no longer use this library so haven't been paying attention for some time-- unless the mirroring happens automatically, I'm likely to get very out of date again...

**Comment by ivg** [comment]
Don't know whether such instructions exist. I would do the following: use the release mechanism of the github and release the latest commit. Then look at the md5 sum of the resulting tar file. If it doesn't match, then either bail out, or upload the archive from the google code as an attached binary.

I don't think that it is out of date as google code is closed and it impossible to change the upstream any more (unless Richard Jones actually created another upstream source)

**Comment by mor1** [comment]
Ok-- so I've grabbed a copy of the exported git repo from the original Google Code Archive, and I've force pushed this over my mirror (as it had a couple of years extra commits). I've also created a tagged released at the commit ref whose commit log message indicates it's Richard's 2.0.4 release. The `.tar.gz` I download from that link is about 50kB smaller than the `.tar.gz` I download from Google Code Archive.

Does that help?

**Comment by ivg** [comment]
Cool! It looks like that the upstream tarball contains some data, like Changes file, and commit ids, that are not present in the source tree by default. The rest is the same (I diffed two tarballs). Since, the mirror must point to a file with the same md5 sum, we need to do the final step. We need to download the tar ball from the upsteam, and attach it to the release. (Go to releases, then click _Edit_ button and use the attach interface to add the upstream tarball). After this is done, we can update opam file, so that it will never fail (or fail with a much less probability).

**Comment by mor1** [comment]
Done, I think!

**Comment by ivg** [comment]
Great, the PR ocaml/opam-repository#7372 is issued!

**Comment by mor1** [comment]
Cool, closing :)
